bugfix: fixes  #448 (#505)
Fixes issue #448 (Trie.mergeDisjoint can produce broken tries)
* actually forces a trap when Trie.mergeDisjoint tries to merge maps
with non disjoint domains (as claimed in the doc).

Unfortunately, the test harness isn't set up to test for traps, but you
manually verify it by running (in dir test)

```

[nix-shell:~/motoko-base/test]$ moc -c --package base ../src -wasi-system-api traps/issue-448.mo 

[nix-shell:~/motoko-base/test]$ wasmtime run --disable-cache issue-448.wasm
Trie.mergeDisjoint
Error: failed to run main module `issue-448.wasm`

Caused by:
    0: failed to invoke command default
    1: wasm trap: wasm `unreachable` instruction executed
       wasm backtrace:
           0: 0x1634 - <unknown>!trap
           1: 0x1618 - <unknown>!anon-func-576.15
           2: 0x1c73 - <unknown>!rec2
           3: 0x1d62 - <unknown>!rec1
           4: 0x1586 - <unknown>!disj
           5: 0x1732 - <unknown>!rec
           6:  0x5eb - <unknown>!mergeDisjoint
           7:  0x57e - <unknown>!init
           8: 0x1f84 - <unknown>!_start
       

```